name: 'Debug workflow'

on: [push]

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # npm install
      - name: install
        run: |
          npm install
        env:
          CI: true
      # build
      - name: Build
        run: |
          npm run build
        env:
          CI: true
      - name: Debug
        uses: ./.github/actions/debug-action
