# 该workflow的名称，可以随意填写
name: release

# workflow的触发事件，这里代表release分支的push事件触发
on:
  push:
    branches: [release]

# 任务
jobs:
  build:
    # 运行所需要的环境
    runs-on: ubuntu-latest

    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # 下载依赖
      - name: install
        run: |
          npm install
        env:
          CI: true
      # 构建
      - name: Build
        run: |
          npm run build
        env:
          CI: true
      # 部署
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: '-avz --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TESTTARGET }}
      # Notify
      - name: Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          avatarUrl: https://avatars.githubusercontent.com/u/71952965?s=400&u=b4330492595a29cdba1c8c3029c078d1cb70631e&v=4
          username: ${{ github.event.head_commit.committer.name }}
          description: 修改内容如下
          details: ${{ github.event.head_commit.message }}
          footer: 更新时间
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: 更新失败
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: 取消更新
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
