# 该workflow的名称，可以随意填写
name: test-deploy

# workflow的触发事件，这里代表release分支的push事件触发
on:
  push:
    branches: [release]

# 任务
jobs:
  build:
    # 运行所需要的环境
    runs-on: ubuntu-latest

    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # npm install
      - name: install
        run: |
          npm install
        env:
          CI: true
      # build
      - name: Build
        run: |
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: '-avz --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TESTTARGET }}
      # Wechat Notification
      - name: Wechat Notification
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}
        with:
          msgtype: markdown
          content: "实时新增用户反馈<font color=\"warning\">132例</font>，请相关同事注意。\n
          > 类型:<font color=\"comment\">用户反馈</font> \n
          > 普通用户反馈:<font color=\"comment\">117例</font> \n
          > VIP用户反馈:<font color=\"comment\">15例</font>"
